/**
 * Demo Graph Data — Notes & Edges
 *
 * Fully enriched with semantic metadata: source quotes, depth levels,
 * knowledge gaps, expansion suggestions, cluster names, and typed edges.
 */

import type { GraphData, GraphNode, GraphEdge, GraphIntelligenceSummary } from '@/types/graph';

const DEMO_NODES: GraphNode[] = [
  // ── Cluster A: Foundations (violet) ─────────────────────────────────────
  {
    id: 'neural-nets',
    label: 'Neural Networks',
    type: 'concept',
    sourceId: 'src-1',
    createdAt: '2026-05-17T00:00:00Z',
    x: -15, y: -175,
    size: 22, centrality: 0.95,
    clusterId: 'cluster-a', clusterColor: '#7B5EA7', clusterName: 'Foundations',
    metadata: {
      summary: 'Neural networks form the architectural foundation of your notes — described as systems that learn by adjusting millions of parameters through iterative optimization until predictions become accurate.',
      sourceQuote: 'A neural network learns by adjusting its weights through backpropagation until the error is minimized. The power comes not from any single neuron but from the hierarchical composition of many simple operations.',
      whyItMatters: 'This is the root concept your entire knowledge structure depends on. Seven of your other concepts — backpropagation, deep learning, feature learning, transformers, gradient descent, training data, and embeddings — only make sense once this is understood.',
      depthLevel: 'mastered',
      gaps: [
        'You explain how neural networks learn but not why deep networks generalize better than shallow ones — the depth advantage is unstated.',
        'No mention of biological inspiration vs. mathematical reality — a common misconception worth addressing.',
      ],
      expansionSuggestions: ['Activation Functions', 'Universal Approximation Theorem', 'Vanishing Gradients'],
    },
  },
  {
    id: 'deep-learning',
    label: 'Deep Learning',
    type: 'concept',
    sourceId: 'src-1',
    createdAt: '2026-05-17T00:00:00Z',
    x: -202, y: -97,
    size: 16, centrality: 0.70,
    clusterId: 'cluster-a', clusterColor: '#7B5EA7', clusterName: 'Foundations',
    metadata: {
      summary: 'Discussed as an extension of neural networks with many stacked layers, enabling automatic extraction of hierarchical features. Your notes position it as the enabler of modern AI breakthroughs.',
      sourceQuote: 'Deep learning adds depth — literally more layers — allowing the network to learn increasingly abstract representations. A shallow network can approximate functions; a deep one can compose them.',
      whyItMatters: 'Acts as a bridge concept between the theoretical neural network model and practical architectures like Transformers. Without this, the jump from "how neurons work" to "how GPT works" is too large.',
      depthLevel: 'explained',
      gaps: [
        'You mention deep learning enables feature learning but do not explain why depth specifically helps — the representation hierarchy argument is missing.',
      ],
      expansionSuggestions: ['Convolutional Neural Networks', 'Recurrent Networks', 'Depth vs Width trade-off'],
    },
  },
  {
    id: 'backprop',
    label: 'Backpropagation',
    type: 'concept',
    sourceId: 'src-1',
    createdAt: '2026-05-17T00:00:00Z',
    x: 4, y: -295,
    size: 13, centrality: 0.55,
    clusterId: 'cluster-a', clusterColor: '#7B5EA7', clusterName: 'Foundations',
    metadata: {
      summary: 'Described as the algorithm that makes training tractable — applying the chain rule backward through layers to compute how each weight should change. Your notes correctly identify it as the "training engine."',
      sourceQuote: 'Backpropagation is just the chain rule applied recursively. For each weight, we compute how much the final error would change if we nudged that weight slightly — then we nudge it in the right direction.',
      whyItMatters: 'Backpropagation is the mechanism that connects loss functions to weight updates — without it, neural networks could not learn. It is the computational glue between gradient descent and the network.',
      depthLevel: 'explained',
      gaps: [
        'The vanishing gradient problem — where backpropagation breaks down in very deep networks — is not addressed despite being one of its most important limitations.',
      ],
      expansionSuggestions: ['Vanishing Gradients', 'Automatic Differentiation', 'Computational Graphs'],
    },
  },
  {
    id: 'feature-learning',
    label: 'Feature Learning',
    type: 'concept',
    sourceId: 'src-1',
    createdAt: '2026-05-17T00:00:00Z',
    x: 160, y: -79,
    size: 13, centrality: 0.52,
    clusterId: 'cluster-a', clusterColor: '#7B5EA7', clusterName: 'Foundations',
    metadata: {
      summary: 'Presented as the key advantage of deep learning over hand-engineered approaches — the ability for networks to automatically discover what features to extract from raw data.',
      sourceQuote: 'Instead of telling the model what to look for, deep learning learns what to look for. Feature engineering becomes feature learning — the network discovers the relevant structure automatically.',
      whyItMatters: 'Connects your foundational neural network knowledge to practical architectures. It explains why embeddings are useful and why transformers can handle language without explicit grammar rules.',
      depthLevel: 'surface',
      gaps: [
        'The relationship between feature learning and transfer learning is not explored — learned features can be reused across tasks, which is a powerful implication.',
      ],
      expansionSuggestions: ['Transfer Learning', 'Representation Learning', 'Feature Visualization'],
    },
  },

  // ── Cluster B: Architectures (forest) ───────────────────────────────────
  {
    id: 'transformer',
    label: 'Transformer',
    type: 'concept',
    sourceId: 'src-1',
    createdAt: '2026-05-17T00:00:00Z',
    x: 322, y: -202,
    size: 19, centrality: 0.82,
    clusterId: 'cluster-b', clusterColor: '#3D8A6E', clusterName: 'Architectures',
    metadata: {
      summary: 'Your notes describe the Transformer as the paradigm-shifting architecture that replaced recurrence with self-attention, enabling parallel training and unprecedented scale.',
      sourceQuote: 'The Transformer got rid of recurrence entirely. Instead of processing tokens sequentially, it computes attention over all tokens simultaneously — making it massively parallelizable and scalable.',
      whyItMatters: 'The most consequential concept in your architecture cluster. Everything modern — BERT, GPT, T5, vision transformers — descends from this architecture. Your understanding here directly enables understanding LLMs.',
      depthLevel: 'explained',
      gaps: [
        'The computational cost of attention (O(n²) with sequence length) and techniques to address it — sparse attention, linear attention — are not covered.',
        'Positional encoding is not mentioned, which is how the Transformer handles sequence order without recurrence.',
      ],
      expansionSuggestions: ['Positional Encoding', 'BERT', 'Vision Transformers', 'Efficient Attention'],
    },
  },
  {
    id: 'attention',
    label: 'Attention Mechanism',
    type: 'concept',
    sourceId: 'src-1',
    createdAt: '2026-05-17T00:00:00Z',
    x: 382, y: -40,
    size: 16, centrality: 0.68,
    clusterId: 'cluster-b', clusterColor: '#3D8A6E', clusterName: 'Architectures',
    metadata: {
      summary: 'Described as the core innovation of the Transformer — a mechanism for each token to dynamically weight how much it should "attend to" every other token in the sequence.',
      sourceQuote: 'Attention computes a weighted sum of all values, where the weights reflect how relevant each position is to the current query. The model learns which parts of the input to focus on for each output.',
      whyItMatters: 'The pivotal concept connecting the Transformer architecture to its power. Understanding attention is necessary to understand why Transformers are better than RNNs for long-range dependencies.',
      depthLevel: 'explained',
      gaps: [
        'Multi-head attention — running multiple attention operations in parallel — is not discussed, even though it is the actual mechanism used in practice.',
      ],
      expansionSuggestions: ['Multi-head Attention', 'Cross-Attention', 'Attention Visualization'],
    },
  },
  {
    id: 'self-attention',
    label: 'Self-Attention',
    type: 'concept',
    sourceId: 'src-1',
    createdAt: '2026-05-17T00:00:00Z',
    x: 316, y: 97,
    size: 12, centrality: 0.46,
    clusterId: 'cluster-b', clusterColor: '#3D8A6E', clusterName: 'Architectures',
    metadata: {
      summary: 'Noted as the specific variant of attention where a sequence attends to itself — each position can relate to every other position within the same sequence.',
      sourceQuote: 'Self-attention means the query, key, and value all come from the same sequence. Each word can look at every other word and decide how relevant it is — giving the model global context at every layer.',
      whyItMatters: 'The mechanism that makes Transformers able to model long-range dependencies that RNNs struggle with. Without this concept, it is unclear why Transformers outperform LSTMs on language tasks.',
      depthLevel: 'surface',
      gaps: [
        'The query/key/value decomposition — the actual matrix operations behind self-attention — is not explained, leaving a gap between "what it does" and "how it works."',
      ],
      expansionSuggestions: ['Query/Key/Value Matrices', 'Scaled Dot-Product Attention', 'Attention Patterns'],
    },
  },
  {
    id: 'embeddings',
    label: 'Embeddings',
    type: 'concept',
    sourceId: 'src-1',
    createdAt: '2026-05-17T00:00:00Z',
    x: 169, y: 169,
    size: 13, centrality: 0.54,
    clusterId: 'cluster-b', clusterColor: '#3D8A6E', clusterName: 'Architectures',
    metadata: {
      summary: 'Described as dense vector representations that map discrete tokens into a continuous space where geometric proximity reflects semantic similarity.',
      sourceQuote: 'Embeddings solve the discrete-to-continuous problem. Instead of one-hot vectors, each word becomes a dense vector of floats — and words with similar meanings end up geometrically close in that space.',
      whyItMatters: 'The bridge between symbolic data (words, categories) and neural computation. Every modern NLP system begins with embeddings. They also directly connect to knowledge graphs — this application node is in your graph.',
      depthLevel: 'explained',
      gaps: [
        'Word2Vec, GloVe, and contextual embeddings (which change per context) are distinct ideas — your notes treat all embeddings as the same thing.',
      ],
      expansionSuggestions: ['Word2Vec', 'Contextual Embeddings', 'Embedding Space Geometry'],
    },
  },

  // ── Cluster C: Training (amber) ──────────────────────────────────────────
  {
    id: 'gradient-descent',
    label: 'Gradient Descent',
    type: 'concept',
    sourceId: 'src-1',
    createdAt: '2026-05-17T00:00:00Z',
    x: -340, y: -154,
    size: 16, centrality: 0.69,
    clusterId: 'cluster-c', clusterColor: '#B06040', clusterName: 'Training',
    metadata: {
      summary: 'Presented as the optimizer — the algorithm that uses the computed gradients to iteratively move weights toward a loss minimum, forming the core of how neural networks learn.',
      sourceQuote: 'Gradient descent moves parameters in the direction that reduces the loss. We take small steps — the learning rate controls how large — and repeat until the loss stops improving.',
      whyItMatters: 'The core learning algorithm that connects backpropagation (which computes the direction) and the loss function (which defines the target). Without gradient descent, computed gradients have nowhere to go.',
      depthLevel: 'explained',
      gaps: [
        'SGD vs. Adam vs. other optimizers are not discussed — in practice, adaptive optimizers like Adam dominate, and the choice matters significantly.',
        'Learning rate schedules and their impact are not covered.',
      ],
      expansionSuggestions: ['Adam Optimizer', 'Learning Rate Schedules', 'Momentum', 'Saddle Points'],
    },
  },
  {
    id: 'loss-function',
    label: 'Loss Function',
    type: 'concept',
    sourceId: 'src-1',
    createdAt: '2026-05-17T00:00:00Z',
    x: -415, y: 7,
    size: 13, centrality: 0.52,
    clusterId: 'cluster-c', clusterColor: '#B06040', clusterName: 'Training',
    metadata: {
      summary: 'Described as the objective function — a scalar measure of how wrong the current predictions are, which the training process seeks to minimize.',
      sourceQuote: 'The loss function quantifies the mistake. For classification we use cross-entropy; for regression, mean squared error. The choice of loss determines what "better" means for the model.',
      whyItMatters: 'Defines what the model is optimizing toward. A poorly chosen loss function produces a model that technically optimizes but behaves badly in practice — the distinction between proxy metrics and true objectives.',
      depthLevel: 'explained',
      gaps: [
        'The relationship between loss functions and probabilistic interpretation (e.g., cross-entropy as negative log-likelihood) is not addressed.',
      ],
      expansionSuggestions: ['Cross-Entropy', 'KL Divergence', 'Contrastive Loss', 'Reward Modeling'],
    },
  },
  {
    id: 'overfitting',
    label: 'Overfitting',
    type: 'concept',
    sourceId: 'src-1',
    createdAt: '2026-05-17T00:00:00Z',
    x: -220, y: 97,
    size: 12, centrality: 0.46,
    clusterId: 'cluster-c', clusterColor: '#B06040', clusterName: 'Training',
    metadata: {
      summary: 'Defined as the failure mode where a model memorizes training data rather than learning generalizable patterns — identifiable by the gap between training and validation performance.',
      sourceQuote: 'Overfitting is when the model learns the training data too well — it memorizes noise instead of signal. Low training loss but high validation loss is the telltale sign.',
      whyItMatters: 'The central tension in machine learning — models must be expressive enough to learn, but not so expressive they memorize. This drives regularization, data augmentation, and evaluation methodology.',
      depthLevel: 'explained',
      gaps: [
        'The bias-variance tradeoff — the theoretical framework explaining why overfitting happens — is not in your notes.',
      ],
      expansionSuggestions: ['Bias-Variance Tradeoff', 'Validation Curves', 'Early Stopping'],
    },
  },
  {
    id: 'regularization',
    label: 'Regularization',
    type: 'concept',
    sourceId: 'src-1',
    createdAt: '2026-05-17T00:00:00Z',
    x: -355, y: 199,
    size: 11, centrality: 0.40,
    clusterId: 'cluster-c', clusterColor: '#B06040', clusterName: 'Training',
    metadata: {
      summary: 'Described as the family of techniques that prevent overfitting by penalizing model complexity, with L1/L2 weight decay and dropout as the primary examples in your notes.',
      sourceQuote: 'Regularization adds a penalty to the loss for having large weights. This forces the model to keep weights small and prevents any single pathway from dominating — making the network more robust.',
      whyItMatters: 'Connects overfitting (the problem) to dropout (a specific technique). Without regularization in your knowledge graph, the path from "problem identified" to "solution applied" would be broken.',
      depthLevel: 'surface',
      gaps: [
        'Data augmentation as a form of regularization — arguably the most effective — is not in your notes.',
        'L1 vs L2 regularization differences (sparsity vs. smoothness) are not distinguished.',
      ],
      expansionSuggestions: ['Data Augmentation', 'L1 vs L2 Regularization', 'Batch Normalization', 'Weight Decay'],
    },
  },
  {
    id: 'training-data',
    label: 'Training Data',
    type: 'concept',
    sourceId: 'src-1',
    createdAt: '2026-05-17T00:00:00Z',
    x: -49, y: 181,
    size: 14, centrality: 0.58,
    clusterId: 'cluster-c', clusterColor: '#B06040', clusterName: 'Training',
    metadata: {
      summary: 'Discussed as the raw material for learning — the labeled examples used to fit model parameters, with implicit acknowledgment that its quality and quantity determine the ceiling of model performance.',
      sourceQuote: 'The model can only learn what is in the training data. Garbage in, garbage out — but more importantly, the distribution of training data determines what the model can and cannot generalize to.',
      whyItMatters: 'Often the most impactful factor in model quality, yet the least theorized in your notes. You cover what the model does with data but not how to collect, clean, or curate it.',
      depthLevel: 'surface',
      gaps: [
        'Data collection, labeling quality, and distribution shift are not covered — these are often more impactful than architectural choices.',
      ],
      expansionSuggestions: ['Distribution Shift', 'Data Curation', 'Synthetic Data', 'Active Learning'],
    },
  },
  {
    id: 'dropout',
    label: 'Dropout',
    type: 'concept',
    sourceId: 'src-1',
    createdAt: '2026-05-17T00:00:00Z',
    x: -202, y: 244,
    size: 10, centrality: 0.35,
    clusterId: 'cluster-c', clusterColor: '#B06040', clusterName: 'Training',
    metadata: {
      summary: 'Noted as a regularization technique that randomly zeroes activations during training, forcing the network to learn redundant representations rather than relying on specific pathways.',
      sourceQuote: 'Dropout randomly "turns off" neurons during training — each forward pass uses a different random subset of the network. This prevents co-adaptation and forces each pathway to be independently useful.',
      whyItMatters: 'A concrete instance of regularization that is widely used in practice. Its connection to ensemble methods — each training pass trains a slightly different sub-network — is an insight that deepens the understanding.',
      depthLevel: 'surface',
      gaps: [
        'The inference-time scaling (weights multiplied by keep probability) is not mentioned — this is easy to get wrong when implementing.',
      ],
      expansionSuggestions: ['DropPath', 'Stochastic Depth', 'Monte Carlo Dropout'],
    },
  },
  {
    id: 'knowledge-graph',
    label: 'Knowledge Graph',
    type: 'concept',
    sourceId: 'src-1',
    createdAt: '2026-05-17T00:00:00Z',
    x: 49, y: 49,
    size: 12, centrality: 0.48,
    clusterId: 'cluster-a', clusterColor: '#7B5EA7', clusterName: 'Foundations',
    metadata: {
      summary: 'Mentioned as an application — a structured representation of entities and relationships encoded as triples, positioned in your notes as where embeddings "live" when mapped to structured knowledge.',
      sourceQuote: 'Knowledge graphs encode what we know as nodes and edges — entities and their relationships. When combined with embeddings, they can support reasoning over structured facts.',
      whyItMatters: 'The most under-developed concept in your graph — only 2 connections. It sits at the intersection of symbolic AI and neural AI, which is a rich area, but your notes only surface the surface.',
      depthLevel: 'surface',
      gaps: [
        'The distinction between knowledge graphs and neural knowledge stores (like model weights) is not drawn.',
        'How knowledge graphs are actually constructed and queried is absent.',
      ],
      expansionSuggestions: ['Knowledge Graph Embeddings', 'Entity Linking', 'GraphRAG', 'Ontologies'],
    },
  },
];

const DEMO_EDGES: GraphEdge[] = [
  { id: 'e1',  sourceId: 'neural-nets',      targetId: 'deep-learning',    label: 'is the basis of',      weight: 0.9,  type: 'semantic', semanticType: 'ENABLES',    createdAt: '2026-05-17T00:00:00Z' },
  { id: 'e2',  sourceId: 'neural-nets',      targetId: 'backprop',         label: 'trained via',           weight: 0.85, type: 'semantic', semanticType: 'DEPENDS_ON', createdAt: '2026-05-17T00:00:00Z' },
  { id: 'e3',  sourceId: 'deep-learning',    targetId: 'feature-learning', label: 'enables',               weight: 0.8,  type: 'semantic', semanticType: 'ENABLES',    createdAt: '2026-05-17T00:00:00Z' },
  { id: 'e4',  sourceId: 'neural-nets',      targetId: 'transformer',      label: 'evolved into',          weight: 0.85, type: 'semantic', semanticType: 'LEADS_TO',   createdAt: '2026-05-17T00:00:00Z' },
  { id: 'e5',  sourceId: 'neural-nets',      targetId: 'gradient-descent', label: 'optimized by',          weight: 0.8,  type: 'semantic', semanticType: 'DEPENDS_ON', createdAt: '2026-05-17T00:00:00Z' },
  { id: 'e6',  sourceId: 'transformer',      targetId: 'attention',        label: 'built on',              weight: 0.95, type: 'semantic', semanticType: 'PART_OF',    createdAt: '2026-05-17T00:00:00Z' },
  { id: 'e7',  sourceId: 'attention',        targetId: 'self-attention',   label: 'variant of',            weight: 0.9,  type: 'semantic', semanticType: 'IS_A',       createdAt: '2026-05-17T00:00:00Z' },
  { id: 'e8',  sourceId: 'self-attention',   targetId: 'embeddings',       label: 'operates on',           weight: 0.75, type: 'semantic', semanticType: 'DEPENDS_ON', createdAt: '2026-05-17T00:00:00Z' },
  { id: 'e9',  sourceId: 'backprop',         targetId: 'gradient-descent', label: 'computes gradients for', weight: 0.9, type: 'semantic', semanticType: 'ENABLES',    createdAt: '2026-05-17T00:00:00Z' },
  { id: 'e10', sourceId: 'gradient-descent', targetId: 'loss-function',    label: 'minimizes',             weight: 0.95, type: 'semantic', semanticType: 'DEPENDS_ON', createdAt: '2026-05-17T00:00:00Z' },
  { id: 'e11', sourceId: 'deep-learning',    targetId: 'overfitting',      label: 'risks',                 weight: 0.7,  type: 'semantic', semanticType: 'CAUSES',     createdAt: '2026-05-17T00:00:00Z' },
  { id: 'e12', sourceId: 'overfitting',      targetId: 'regularization',   label: 'addressed by',          weight: 0.9,  type: 'semantic', semanticType: 'LEADS_TO',   createdAt: '2026-05-17T00:00:00Z' },
  { id: 'e13', sourceId: 'regularization',   targetId: 'dropout',          label: 'technique includes',    weight: 0.8,  type: 'semantic', semanticType: 'PART_OF',    createdAt: '2026-05-17T00:00:00Z' },
  { id: 'e14', sourceId: 'feature-learning', targetId: 'embeddings',       label: 'produces',              weight: 0.8,  type: 'semantic', semanticType: 'ENABLES',    createdAt: '2026-05-17T00:00:00Z' },
  { id: 'e15', sourceId: 'embeddings',       targetId: 'knowledge-graph',  label: 'represents structure in', weight: 0.7, type: 'semantic', semanticType: 'RELATES_TO', createdAt: '2026-05-17T00:00:00Z' },
  { id: 'e16', sourceId: 'training-data',    targetId: 'overfitting',      label: 'volume affects',        weight: 0.7,  type: 'semantic', semanticType: 'CAUSES',     createdAt: '2026-05-17T00:00:00Z' },
  { id: 'e17', sourceId: 'training-data',    targetId: 'deep-learning',    label: 'feeds',                 weight: 0.8,  type: 'semantic', semanticType: 'ENABLES',    createdAt: '2026-05-17T00:00:00Z' },
  { id: 'e18', sourceId: 'knowledge-graph',  targetId: 'transformer',      label: 'informs',               weight: 0.6,  type: 'semantic', semanticType: 'RELATES_TO', createdAt: '2026-05-17T00:00:00Z' },
  { id: 'e19', sourceId: 'loss-function',    targetId: 'backprop',         label: 'error signal for',      weight: 0.85, type: 'semantic', semanticType: 'ENABLES',    createdAt: '2026-05-17T00:00:00Z' },
  { id: 'e20', sourceId: 'training-data',    targetId: 'embeddings',       label: 'encoded as',            weight: 0.65, type: 'semantic', semanticType: 'LEADS_TO',   createdAt: '2026-05-17T00:00:00Z' },
];

const DEMO_INTELLIGENCE_SUMMARY: GraphIntelligenceSummary = {
  strongAreas: ['Neural network mechanics', 'Training optimization', 'Transformer architecture'],
  weakAreas: ['Model evaluation', 'Practical deployment', 'Data engineering'],
  mainConcept: 'neural-nets',
  mostIsolatedConcept: 'knowledge-graph',
  gaps: [
    'No evaluation concepts — precision, recall, F1, AUC are entirely absent despite being essential to understanding when a model is good',
    'Knowledge Graph appears isolated with only 2 connections, suggesting surface-level coverage of a rich area',
    'The bias-variance tradeoff — the theoretical framework for overfitting — is missing despite overfitting being in your notes',
    'Optimizer variants (Adam, AdaGrad) are absent; gradient descent appears as if there is only one kind',
  ],
  suggestion: 'Add your notes on model evaluation metrics — you have strong coverage of how models train but no framework for judging whether they are actually good.',
  overview: 'Strong foundational understanding of neural network mechanics with particular depth in training optimization and transformer architecture. The conceptual chain from neural networks → backpropagation → gradient descent → loss function is well-formed. The main structural gap is the complete absence of evaluation — you know how to build and train models but lack the measurement side. Knowledge graphs are under-connected relative to their potential role in your domain.',
};

export const DEMO_GRAPH: GraphData = {
  id: 'demo-1',
  userId: 'demo-user',
  name: 'Machine Learning Concepts',
  nodeCount: DEMO_NODES.length,
  edgeCount: DEMO_EDGES.length,
  createdAt: '2026-05-17T00:00:00Z',
  updatedAt: '2026-05-17T00:00:00Z',
  nodes: DEMO_NODES,
  edges: DEMO_EDGES,
  intelligenceSummary: DEMO_INTELLIGENCE_SUMMARY,
};

export const DEMO_EXPANSION_NODES: GraphNode[] = [
  {
    id: 'llm', label: 'Large Language Models', type: 'concept', sourceId: 'src-2',
    createdAt: '2026-05-17T00:01:00Z',
    x: 0, y: 0, size: 18, centrality: 0.75,
    clusterId: 'cluster-b', clusterColor: '#3D8A6E', clusterName: 'Architectures',
    metadata: {
      summary: 'Transformer-based models trained at web scale, exhibiting emergent abilities including few-shot learning and reasoning.',
      sourceQuote: 'LLMs are just Transformers trained on a lot of text. The emergent abilities — reasoning, code generation, translation — were not explicitly programmed; they arose from scale.',
      whyItMatters: 'The culmination of your architecture cluster — Transformer → LLM completes the conceptual arc from mechanism to deployed system.',
      depthLevel: 'explained',
      gaps: ['Scaling laws and why size matters is not discussed.'],
      expansionSuggestions: ['Scaling Laws', 'Emergent Abilities', 'Constitutional AI'],
    },
  },
  {
    id: 'fine-tuning', label: 'Fine-tuning', type: 'concept', sourceId: 'src-2',
    createdAt: '2026-05-17T00:01:00Z',
    x: 0, y: 0, size: 13, centrality: 0.51,
    clusterId: 'cluster-b', clusterColor: '#3D8A6E', clusterName: 'Architectures',
    metadata: {
      summary: 'Adapting a pre-trained model to a specific task by continuing training on task-specific data at a low learning rate.',
      sourceQuote: 'Fine-tuning takes a pre-trained model and continues training on your specific task. The key is using a very low learning rate — you want to adapt, not overwrite the pre-trained knowledge.',
      whyItMatters: 'Connects pre-training (LLMs) to practical deployment. Explains how general-purpose models become specialized tools.',
      depthLevel: 'surface',
      gaps: ['Parameter-efficient fine-tuning methods (LoRA, adapters) are not mentioned.'],
      expansionSuggestions: ['LoRA', 'Instruction Tuning', 'Few-shot Prompting'],
    },
  },
  {
    id: 'prompt-engineering', label: 'Prompt Engineering', type: 'concept', sourceId: 'src-2',
    createdAt: '2026-05-17T00:01:00Z',
    x: 0, y: 0, size: 12, centrality: 0.47,
    clusterId: 'cluster-b', clusterColor: '#3D8A6E', clusterName: 'Architectures',
    metadata: {
      summary: 'Designing inputs that elicit desired behaviors from frozen language models by leveraging in-context learning.',
      sourceQuote: 'Prompt engineering is about knowing how to ask. The same model gives wildly different answers depending on how the question is framed — structure, examples, and wording all matter.',
      whyItMatters: 'The practical interface between LLMs and applications. Contrasts interestingly with fine-tuning — both are ways to specialize a model, but one changes weights and one does not.',
      depthLevel: 'surface',
      gaps: ['Chain-of-thought prompting and its effect on reasoning is not covered.'],
      expansionSuggestions: ['Chain-of-Thought', 'ReAct', 'Retrieval-Augmented Generation'],
    },
  },
  {
    id: 'rlhf', label: 'RLHF', type: 'concept', sourceId: 'src-2',
    createdAt: '2026-05-17T00:01:00Z',
    x: 0, y: 0, size: 11, centrality: 0.42,
    clusterId: 'cluster-c', clusterColor: '#B06040', clusterName: 'Training',
    metadata: {
      summary: 'Reinforcement Learning from Human Feedback — aligning model behavior with human preferences by training a reward model on human comparisons.',
      sourceQuote: 'RLHF adds a human-in-the-loop. Humans compare model outputs, those comparisons train a reward model, and the reward model guides further training via RL. It is how ChatGPT learned to be helpful.',
      whyItMatters: 'Closes the loop from training (gradient descent) to alignment (human values). A missing piece in understanding why modern AI assistants behave differently from raw language models.',
      depthLevel: 'surface',
      gaps: ['RLHF vs. RLAIF (AI feedback) and constitutional approaches are not covered.'],
      expansionSuggestions: ['Constitutional AI', 'DPO', 'Reward Hacking'],
    },
  },
  {
    id: 'context-window', label: 'Context Window', type: 'concept', sourceId: 'src-2',
    createdAt: '2026-05-17T00:01:00Z',
    x: 0, y: 0, size: 11, centrality: 0.40,
    clusterId: 'cluster-b', clusterColor: '#3D8A6E', clusterName: 'Architectures',
    metadata: {
      summary: 'The maximum sequence length a Transformer can attend to — a hard constraint determined by the quadratic cost of self-attention.',
      sourceQuote: 'The context window is how much the model can see at once. Self-attention is O(n²) — doubling the context quadruples the computation. This is why 1M-token contexts are expensive to achieve.',
      whyItMatters: 'Directly explains the limitation of the Transformer\'s O(n²) attention cost. Connects your attention knowledge to practical deployment constraints.',
      depthLevel: 'surface',
      gaps: ['Flash attention and other efficient attention mechanisms that extend the context window are not covered.'],
      expansionSuggestions: ['Flash Attention', 'Ring Attention', 'Retrieval-Augmented Generation'],
    },
  },
];

export const DEMO_EXPANSION_EDGES: GraphEdge[] = [
  { id: 'ex1', sourceId: 'transformer',        targetId: 'llm',               label: 'is the foundation of',  weight: 0.95, type: 'semantic', semanticType: 'ENABLES',    createdAt: '2026-05-17T00:01:00Z' },
  { id: 'ex2', sourceId: 'llm',                targetId: 'fine-tuning',       label: 'specialized via',       weight: 0.85, type: 'semantic', semanticType: 'LEADS_TO',   createdAt: '2026-05-17T00:01:00Z' },
  { id: 'ex3', sourceId: 'llm',                targetId: 'prompt-engineering', label: 'guided by',            weight: 0.8,  type: 'semantic', semanticType: 'DEPENDS_ON', createdAt: '2026-05-17T00:01:00Z' },
  { id: 'ex4', sourceId: 'fine-tuning',        targetId: 'rlhf',              label: 'improved by',           weight: 0.85, type: 'semantic', semanticType: 'LEADS_TO',   createdAt: '2026-05-17T00:01:00Z' },
  { id: 'ex5', sourceId: 'attention',          targetId: 'context-window',    label: 'determines limit of',  weight: 0.75, type: 'semantic', semanticType: 'CAUSES',     createdAt: '2026-05-17T00:01:00Z' },
  { id: 'ex6', sourceId: 'llm',                targetId: 'knowledge-graph',   label: 'can build',            weight: 0.7,  type: 'semantic', semanticType: 'ENABLES',    createdAt: '2026-05-17T00:01:00Z' },
  { id: 'ex7', sourceId: 'prompt-engineering', targetId: 'fine-tuning',       label: 'contrasts with',       weight: 0.65, type: 'semantic', semanticType: 'CONTRASTS',  createdAt: '2026-05-17T00:01:00Z' },
];
